# Generated by Django 3.0.7 on 2020-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0002_auto_20200618_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memepost',
            name='image',
            field=models.ImageField(upload_to='meme_images/'),
        ),
    ]
