# Generated by Django 3.0.7 on 2020-06-18 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0003_auto_20200618_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='memepost',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
