# Generated by Django 3.0.7 on 2020-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0005_memecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memepost',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='MemeComment',
        ),
    ]
