# Generated by Django 3.0.7 on 2020-06-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0006_auto_20200619_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memepost',
            name='comment',
        ),
    ]
