# Generated by Django 3.0.7 on 2020-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0008_memecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecomments',
            name='meme_id',
            field=models.IntegerField(default=1),
        ),
    ]
