# Generated by Django 3.0.7 on 2020-06-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0010_auto_20200619_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecomments',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meme_site.MemePost'),
        ),
    ]
