# Generated by Django 3.0.7 on 2020-06-21 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme_site', '0013_memepost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='memepost',
            name='thumb_down',
            field=models.ManyToManyField(blank=True, related_name='liked_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memepost',
            name='thumb_up',
            field=models.ManyToManyField(blank=True, related_name='liked_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
