# Generated by Django 3.0.7 on 2020-06-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0014_auto_20200621_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memepost',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
