# Generated by Django 3.0.7 on 2020-06-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_site', '0017_remove_memepost_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memepost',
            options={'ordering': ['-date_added']},
        ),
    ]
